-- Migration para criar a tabela de pagamentos no Supabase

CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment TEXT NOT NULL,
    tenant_name TEXT NOT NULL,
    payment_date DATE NOT NULL,
    payment_type TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir acesso anônimo (ajuste conforme necessário para produção)
CREATE POLICY "Permitir acesso total para todos" ON public.payments
    FOR ALL
    USING (true)
    WITH CHECK (true);
